# MySQL 配置
[mysql]
host = localhost
user = root
password = 123456
database = subjects_kg

# Redis 配置
[redis]
host = localhost
port = 6379
password = 1234
db = 0

# 日志配置
[logger]
log_file = logs/app.log

# 文本切分配置
[chunking]
parent_chunk_size = 1500
child_chunk_size = 500
chunk_overlap = 200

# Milvus 向量数据库配置
[milvus]
host = localhost
port = 19530
database_name = default
collection_name = edu_rag

# 检索配置
[retrieval]
retrieval_k = 20
candidate_m = 5


# LLM 配置
[llm]
model_name = mimo-v2.5
dashscope_base_url = https://api.xiaomimimo.com/v1
dashscope_api_key = sk-cd2h7ryerlpd0s60f4zoxyxwmwo2gy854p2tfc53rf1iscqg

# 其他配置
[app]
CUSTOMER_SERVICE_PHONE = 12345678